### ISSUE TITLE
[oracle_user] state="empty" isn't working with materialized view

### ISSUE THREAD

**Issue by ari-stark** [ari-stark/ansible-oracle-modules#1]
On module _oracle_user_, when using `state="empty"` on a schema with materialized views, the module is executing the query `drop table` to drop these views.

The query has to be `drop materialized view`.

**Comment by olfaz** [comment]
there is no deletion of the triggers when  using state="empty" on a schema.

**Comment by ari-stark** [comment]
Fix in version 1.2.1.
https://github.com/ari-stark/ansible-oracle-modules/commit/e65321e671cf5155c0b86a17ee658c030c32b944
